# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: scrape kings league infojobs website

on:
  workflow_dispatch:
  
  repository_dispatch:
    - webhook
    
  schedule:
    - cron: "0 8 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm test
      - uses: pnpm/action-setup@v2
        with:
          version: 7.19.0
      - run: |
          node scraping/leaderboard.js
          git config user.name Diego-Fdez
          git add -A
          git commit -m "[bot] update kings league database"
          git push -u origin main


